---
title: "EPI Info CDC"
author: "Nick Lauerman"
date: "3/16/2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
  html_document: 
    df_print: tibble
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries Used
```{r libraries}
library(tidyverse)
library(lubridate)
```

# Load CDC data
## Read CSV File
```{r read, message=FALSE}
cdc <- read_csv(file = "./data/CDC_data.csv")
```

## Clean data and calculate cumulative number of cases

```{r clean}
names(cdc)[1:2] <-  c("Date",
                      "Number of new cases")
cdc$cum <- cumsum(cdc$`Number of new cases`)
cdc$Date <- as.Date(cdc$Date,
                    format = "%d-%b-%y")
cdc$`Week Number` <- week(cdc$Date)
```


# Visualize all data
```{r, echo=FALSE}
epi <- ggplot(data = cdc)
```
```{r, fig.cap="Epi curve 1", echo=FALSE}
epi + geom_point(aes(x = Date,
              y = `Number of new cases`))+
     geom_smooth(aes(x = Date,
              y = `Number of new cases`),
              color = "red",
              fill = "blue") +
     labs(y = "Cases",
          title = "Number of New Cases of COVID-19 Reported to the CDC")
```
```{r, fig.cap="Epi curve 2, traditional", echo=FALSE}
epi + geom_col(aes(x=Date,
                   y=`Number of new cases`),
               fill= "blue") +
     geom_smooth(aes(x=Date,
                   y=`Number of new cases`),
                 color = "red") +
     labs(y = "Cases",
          title = "Number of New Cases of COVID-19 Reported to the CDC")
```

```{r, fig.cap="Cumulative cases", echo=FALSE}
epi + geom_point(aes(x = Date,
              y = cum))+
    # geom_line(aes(x = Date,
              #y = `cum`)) +
     geom_smooth(aes(x = Date,
              y = `cum`),
              color = "red",
              fill = "blue") +
     labs(y = "Cumulative number of cases",
          title = "Cumulative Number of Cases of COVID-19 Reported to the CDC") +
     geom_hline(yintercept = mean(cdc$cum)) +
     geom_hline(yintercept = median(cdc$cum),
                lty = 2)
```

```{r, fig.cap="Growth Rate", echo=FALSE}
gr <- cdc %>%
  filter(`Number of new cases` != 0)

ggplot(data = gr) +
  geom_line(aes(y = `Number of new cases`,
                    x = cum)) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(aes(y = `Number of new cases`,
                    x = cum)) +
  labs(title = "Daily Growth Rate",
       x = "Total Cases (log)",
       y = "New Cases (log)")

```

```{r, fig.cap="weekly growth rate", echo=FALSE}
gr <- cdc %>%
     group_by(`Week Number`) %>%
     summarise(cases = sum(`Number of new cases`),
               cs = sum(cum),
               count = n())

ggplot(data = gr) +
     geom_line(aes(y = `cases`,
                   x = cs)) + 
     geom_point(aes(y = `cases`,
                    x = cs)) +
     scale_x_log10() +
     scale_y_log10() +
     geom_smooth(aes(y = `cases`,
                     x = cs)) +
  labs(title = "Weekly Growth Rate",
       x = "Total Cases (log)",
       y = "New Cases (log)")

```



# Filter to remove incomplete reporting

remove dates on or after 3 April as this data may not be completely reported          
```{r}
cdc <- cdc %>%                                                                          # update with good date
     filter(Date < as.Date("2020-04-03"))
```

## Visualize
```{r, echo=FALSE}
epi <- ggplot(data = cdc)
```
```{r, fig.cap="stable Epi curve", echo=FALSE}
epi + geom_point(aes(x = Date,
              y = `Number of new cases`))+
     geom_smooth(aes(x = Date,
              y = `Number of new cases`),
              color = "red",
              fill = "blue") +
     labs(y = "Cases",
          title = "Number of New Cases of COVID-19 Reported to the CDC")
```

```{r, fig.cap="stable Epi curve, traditional", echo=FALSE}
epi + geom_col(aes(x=Date,
                   y=`Number of new cases`),
               fill= "blue") +
     geom_smooth(aes(x=Date,
                   y=`Number of new cases`),
                 color = "red") +
     labs(y = "Cases",
          title = "Number of New Cases of COVID-19 Reported to the CDC")
```

```{r, fig.cap="stable Cumulative cases", echo=FALSE}
epi + geom_point(aes(x = Date,
                     y = cum))+
  geom_smooth(aes(x = Date,
                  y = `cum`),
              color = "red",
              fill = "blue") +
  labs(y = "Cumulative number of cases",
       title = "Cumulative Number of Cases of COVID-19 Reported to the CDC") +
  geom_hline(yintercept = mean(cdc$cum)) +
  geom_hline(yintercept = median(cdc$cum),
             lty = 2)
```

```{r, fig.cap="stable Growth Rate", echo=FALSE}
gr <- cdc %>%
  filter(`Number of new cases` != 0)
ggplot(data = gr) +
  geom_line(aes(y = `Number of new cases`,
                    x = cum)) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(aes(y = `Number of new cases`,
                    x = cum)) +
  labs(title = "Daily Growth Rate",
       x = "Total Cases (log)",
       y = "New Cases (log)")


```

```{r, fig.cap="stable weekly growth rate", echo=FALSE}
gr <- cdc %>%
     group_by(`Week Number`) %>%
     summarise(cases = sum(`Number of new cases`),
               cs = sum(cum),
               count = n())

ggplot(data = gr) +
     geom_line(aes(y = `cases`,
                   x = cs)) + 
     geom_point(aes(y = `cases`,
                    x = cs)) +
     scale_x_log10() +
     scale_y_log10() +
     geom_smooth(aes(y = `cases`,
                     x = cs)) +
  labs(title = "Weekly Growth Rate",
       x = "Total Cases (log)",
       y = "New Cases (log)")
```
