---
title: "Data Explorer for Our World in Data COVID dataset"
author: "Nick Lauerman"
date: "as of 5-November-2020"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
    fig_width: 6.5
    fig_height: 6.5
    fig_caption: yes
  word_document: 
    toc: yes
    toc_depth: 4
    fig_width: 6.5
    fig_height: 6.5
    fig_caption: yes
  pdf_document: 
    toc: yes
    toc_depth: 4
    fig_height: 6.5
    fig_width: 6.5
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r libraries,echo = TRUE, include=FALSE}
library(tidyverse)
library(lubridate)
```

<!-- # Read Data -->
```{r get data,echo = FALSE, include=FALSE}
epi_info <- read_csv(file = "./data/Our World Data/full_data.csv")
locations <- read_csv(file = "./data/Our World Data/locations.csv")
```
<!-- ## Country Data -->
```{r,echo = FALSE, include=FALSE}
US <- epi_info %>%
  filter(location == "United States") %>%
  filter(new_cases >= 0)
China <- epi_info %>%
  filter(location == "China") %>%
  filter(new_cases >= 0) %>%
  filter(new_cases < 5000)
World <- epi_info %>%
  filter(location == "World") %>%
  filter(new_cases >= 0)
Germany <- epi_info %>%
  filter(location == "Germany") %>%
  filter(new_cases >= 0)
Italy <- epi_info %>%
  filter(location == "Italy") %>%
  filter(new_cases >= 0)
UK <- epi_info %>%
  filter(location == "United Kingdom") %>%
  filter(new_cases > 0)
Spain <- epi_info %>%
  filter(location == "Spain") %>%
  filter(new_cases > 0)
Canada <- epi_info %>%
  filter(location == "Canada") %>%
  filter(new_cases >= 0) %>%
  filter(new_cases < 2500)
Mexico <- epi_info %>%
  filter(location == "Mexico") %>%
  filter(new_cases >= 0)
Ireland <- epi_info %>%
  filter(location == "Ireland") %>%
  filter(new_cases >= 0)
CostaRica <- epi_info %>%
  filter(location == "Costa Rica") %>%
  filter(new_cases > 0)
India <- epi_info %>%
  filter(location == "India") %>%
  filter(new_cases >= 0)
Ireland <- epi_info %>%
  filter(location == "Ireland") %>%
  filter(new_cases >= 0)

France <- epi_info %>%
  filter(location == "France") %>%
  filter(new_cases >= 0)
```

# Plot

## World
```{r World, fig.cap= "World wide new cases", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = World) +
  geom_point() +
  ggtitle("World wide new cases")
```

```{r, fig.cap= "World Wide New Cases with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = World) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("World Wide New Cases with trend line")
```

```{r, fig.cap= "World wide total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = World) +
  geom_point() +
  ggtitle("World wide total cases")
```

<!-- ```{r, fig.cap= "World Wide total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = World) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x)+ -->
<!--   ggtitle("World Wide total Cases with trend line") -->
<!-- ``` -->

```{r, fig.cap="World wide new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = World) +
  geom_point()+
  ggtitle("World wide new deaths")
```

```{r, fig.cap="World wide new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = World) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x)+
  ggtitle("World wide new deaths with trending")
```

```{r, fig.cap="World wide total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = World) +
  geom_point() +
  ggtitle("World wide total deaths")
```

<!-- ```{r, fig.cap= "World Wide total deaths with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_deaths), data = World) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x)+ -->
<!--   ggtitle("World Wide total deaths with trend line") -->
<!-- ``` -->


## Countries of Interest
### US
```{r US, fig.cap= "US", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = US) +
  geom_point()  +
  ggtitle("US")
```

```{r, fig.cap= "US with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = US) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("US with trend line")
```

```{r, fig.cap= "US total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = US) +
  geom_point()  +
  ggtitle("US total cases")
```

<!-- ```{r, fig.cap= "US total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = US) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("US total Cases with trend line") -->
<!-- ``` -->

```{r, fig.cap="US new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = US) +
  geom_point() +
  ggtitle("US new deaths")
```

```{r, fig.cap="US new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = US) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("US new deaths with trending")
```

```{r, fig.cap= "US total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = US) +
  geom_point()  +
  ggtitle("US total deaths")
```

<!-- ```{r, fig.cap= "US total deaths with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_deaths), data = US) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("US total deaths with trend line") -->
<!-- ``` -->

### Germany
```{r Germany, fig.cap= "Germany", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Germany) +
  geom_point() +
  ggtitle("Germany")
```

```{r, fig.cap= "Germany with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Germany) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Germany with trend line")
```

```{r, fig.cap= "Germany total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Germany) +
  geom_point()  +
  ggtitle("Germany total cases")
```

<!-- ```{r, fig.cap= "Germany total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = Germany) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("Germany total Cases with trend line") -->
<!-- ``` -->

```{r, fig.cap="Germany new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Germany) +
  geom_point() +
  ggtitle("Germany new deaths")
```

```{r, fig.cap="Germany new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Germany) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Germany new deaths with trending")
```

```{r, fig.cap= "Germany total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = Germany) +
  geom_point()  +
  ggtitle("Germany total deaths")
```

### India

```{r India, fig.cap= "India", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = India) +
  geom_point() +
  ggtitle("India")
```

```{r, fig.cap= "India with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = India) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle( "India with trend line")
```

```{r, fig.cap= "India total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = India) +
  geom_point()  +
  ggtitle("India total cases")
```

<!-- ```{r, fig.cap= "India total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = India) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("India total Cases with trend line") -->
<!-- ``` -->

```{r, fig.cap="India new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = India) +
  geom_point() +
  ggtitle("India new deaths")
```

```{r, fig.cap="India new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = India) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("India new deaths with trending")
```

```{r, fig.cap= "India total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = India) +
  geom_point()  +
  ggtitle("India total deaths")
```

<!-- ## Other Countries -->
<!-- ### China -->
<!-- ```{r Other China, fig.cap= "China", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_cases), data = China) + -->
<!--   geom_point() + -->
<!--   ggtitle("China") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "China with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_cases), data = China) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("China with trend line") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "China total cases", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = China) + -->
<!--   geom_point() + -->
<!--   ggtitle("China total cases") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "China total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = China) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("China total Cases with trend line") -->
<!-- ``` -->

<!-- ```{r, fig.cap="China new deaths", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_deaths), data = China) + -->
<!--   geom_point() + -->
<!--   ggtitle("China new deaths",) -->
<!-- ``` -->

<!-- ```{r, fig.cap="China new deaths with trending", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_deaths), data = China) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("China new deaths with trending") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "China total deaths", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_deaths), data = China) + -->
<!--   geom_point() + -->
<!--   ggtitle("China total deaths") -->
<!-- ``` -->

### Italy
```{r Italy, fig.cap= "Italy", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Italy) +
  geom_point() +
  ggtitle("Italy")
```

```{r, fig.cap= "Italy with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Italy) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Italy with trend line")
```

```{r, fig.cap= "Italy total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Italy) +
  geom_point() +
  ggtitle("Italy total cases")
```

```{r, fig.cap= "Italy total Cases with trend line", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Italy) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Italy total Cases with trend line")
```

```{r, fig.cap="Italy new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Italy) +
  geom_point()  +
  ggtitle("Italy new deaths")
```

```{r, fig.cap="Italy new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Italy) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x)  +
  ggtitle("Italy new deaths with trending")
```

```{r, fig.cap= "Italy total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = Italy) +
  geom_point()  +
  ggtitle("Italy total deaths")
```

### Spain
```{r Spain, fig.cap= "Spain", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Spain) +
  geom_point() +
  ggtitle("Spain")
```

```{r, fig.cap= "Spain with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Spain) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Spain with trend line")
```

```{r, fig.cap= "Spain total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Spain) +
  geom_point() +
  ggtitle("Spain total cases")
```

```{r, fig.cap= "Spain total Cases with trend line", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Spain) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Spain total Cases with trend line")
```

```{r, fig.cap="Spain new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Spain) +
  geom_point() +
  ggtitle("Spain new deaths")
```

```{r, fig.cap="Spain new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Spain) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Spain new deaths with trending")
```

```{r, fig.cap= "Spain total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = Spain) +
  geom_point() +
  ggtitle("Spain total deaths")
```

<!-- ### Mexico -->
<!-- ```{r Mexico, fig.cap= "Mexico", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_cases), data = Mexico) + -->
<!--   geom_point() + -->
<!--   ggtitle("Mexico") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Mexico with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_cases), data = Mexico) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("Mexico with trend line") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Mexico total cases", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = Mexico) + -->
<!--   geom_point()  + -->
<!--   ggtitle("Mexico total cases") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Mexico total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = Mexico) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle( "Mexico total Cases with trend line") -->
<!-- ``` -->

<!-- ```{r, fig.cap="Mexico new deaths", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_deaths), data = Mexico) + -->
<!--   geom_point() + -->
<!--   ggtitle("Mexico new deaths") -->
<!-- ``` -->

<!-- ```{r, fig.cap="Mexico new deaths with trending", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_deaths), data = Mexico) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("Mexico new deaths with trending") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Mexico total deaths", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_deaths), data = Mexico) + -->
<!--   geom_point()  + -->
<!--   ggtitle("Mexico total deaths") -->
<!-- ``` -->

<!-- ### Canada -->
<!-- ```{r Canada, fig.cap= "Canada", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_cases), data = Canada) + -->
<!--   geom_point() + -->
<!--   ggtitle("Canada") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Canada with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_cases), data = Canada) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x) + -->
<!--   ggtitle("Canada with trend line") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Canada total cases", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = Canada) + -->
<!--   geom_point()  + -->
<!--   ggtitle("Canada total cases") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Canada total Cases with trend line", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_cases), data = Canada) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x)  + -->
<!--   ggtitle("Canada total Cases with trend line") -->
<!-- ``` -->

<!-- ```{r, fig.cap="Canada new deaths", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_deaths), data = Canada) + -->
<!--   geom_point()  + -->
<!--   ggtitle("Canada new deaths") -->
<!-- ``` -->

<!-- ```{r, fig.cap="Canada new deaths with trending", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=new_deaths), data = Canada) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess", -->
<!--               formula = y~x)  + -->
<!--   ggtitle("Canada new deaths with trending") -->
<!-- ``` -->

<!-- ```{r, fig.cap= "Canada total deaths", echo=FALSE} -->
<!-- ggplot(aes(x = date, y=total_deaths), data = Canada) + -->
<!--   geom_point()  + -->
<!--   ggtitle("Canada total deaths") -->
<!-- ``` -->


### Ireland
```{r Ireland, fig.cap= "Ireland", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Ireland) +
  geom_point() +
  ggtitle("Ireland")
```

```{r, fig.cap= "Ireland with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = Ireland) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Ireland with trend line")
```

```{r, fig.cap= "Ireland total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Ireland) +
  geom_point() +
  ggtitle("Ireland total cases")
```

```{r, fig.cap= "Ireland total Cases with trend line", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = Ireland) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("Ireland total Cases with trend line")
```

```{r, fig.cap="Ireland new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Ireland) +
  geom_point()  +
  ggtitle("Ireland new deaths")
```

```{r, fig.cap="Ireland new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = Ireland) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x)  +
  ggtitle("Ireland new deaths with trending")
```

```{r, fig.cap= "Ireland total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = Italy) +
  geom_point()  +
  ggtitle("Ireland total deaths")
```


### France
```{r France, fig.cap= "France", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = France) +
  geom_point() +
  ggtitle("France")
```

```{r, fig.cap= "France with trend line", echo=FALSE}
ggplot(aes(x = date, y=new_cases), data = France) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("France with trend line")
```

```{r, fig.cap= "France total cases", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = France) +
  geom_point() +
  ggtitle("France total cases")
```

```{r, fig.cap= "France total Cases with trend line", echo=FALSE}
ggplot(aes(x = date, y=total_cases), data = France) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x) +
  ggtitle("France total Cases with trend line")
```

```{r, fig.cap="France new deaths", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = France) +
  geom_point()  +
  ggtitle("France new deaths")
```

```{r, fig.cap="France new deaths with trending", echo=FALSE}
ggplot(aes(x = date, y=new_deaths), data = France) +
  geom_point() +
  geom_smooth(method = "loess",
              formula = y~x)  +
  ggtitle("France new deaths with trending")
```

```{r, fig.cap= "France total deaths", echo=FALSE}
ggplot(aes(x = date, y=total_deaths), data = France) +
  geom_point()  +
  ggtitle("France total deaths")
```

